version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "PLACEHOLDER_FOR_TASK_DEFINITION_ARN"
        LoadBalancerInfo:
          ContainerName: "bianca-app-backend"
          ContainerPort: 3000
        PlatformVersion: "LATEST"
