version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: us-east-2
    AWS_ACCOUNT_ID: 730335291008
    REPOSITORY_NAME_APP: bianca-app-backend
    REPOSITORY_NAME_ASTERISK: bianca-app-asterisk
    APP_CONTAINER_NAME: bianca-app-backend
    ASTERISK_CONTAINER_NAME: asterisk
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI_APP=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME_APP
      - REPOSITORY_URI_ASTERISK=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME_ASTERISK
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)-$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo Build started on $(date)
      - docker build -t $REPOSITORY_URI_APP:$IMAGE_TAG -f Dockerfile .
      - docker tag $REPOSITORY_URI_APP:$IMAGE_TAG $REPOSITORY_URI_APP:latest
      - docker build -t $REPOSITORY_URI_ASTERISK:$IMAGE_TAG -f ./devops/asterisk/Dockerfile ./devops/asterisk
      - docker tag $REPOSITORY_URI_ASTERISK:$IMAGE_TAG $REPOSITORY_URI_ASTERISK:latest
  post_build:
    commands:
      - echo Build completed on $(date)
      - docker push $REPOSITORY_URI_APP:$IMAGE_TAG
      - docker push $REPOSITORY_URI_APP:latest
      - docker push $REPOSITORY_URI_ASTERISK:$IMAGE_TAG
      - docker push $REPOSITORY_URI_ASTERISK:latest
      - echo Creating imagedefinitions.json
      - echo "[{\"name\":\"$APP_CONTAINER_NAME\",\"imageUri\":\"$REPOSITORY_URI_APP:$IMAGE_TAG\"},{\"name\":\"$ASTERISK_CONTAINER_NAME\",\"imageUri\":\"$REPOSITORY_URI_ASTERISK:$IMAGE_TAG\"}]" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json