# ./devops/ngrok-config/ngrok.yml
version: "2"
# Reads the auth token from the environment variable passed in docker-compose.dev.yml
# Ensure NGROK_AUTHTOKEN is set in your .env file
authtoken: 1pVALO0keXNlWh0ihHjHmgGUyEL_26pGVhd9s1k3USnkbiDj5
# Log to stdout so 'docker logs ngrok' shows useful info
log_level: info
log: stdout

tunnels:
  # Tunnel for your web app (HTTP)
  # Targets the 'bianca-app' service on port 3000 within the Docker network
  bianca-app-http:
    proto: http
    addr: bianca-app:3000
    subdomain: my-bianca-dev

  # Tunnel for Asterisk (TCP)
  # Targets the 'asterisk' service on port 5060 within the Docker network
  # asterisk-sip:
  #   proto: tcp
  #   addr: asterisk:5060
  #   remote_addr: 1.tcp.us-cal-1.ngrok.io:24668